### ISSUE TITLE
Allow non-cubic world areas

### ISSUE THREAD

**Issue by nuriofernandez** [xXNurioXx/GrechWorldAreas#1]
Make necessary changes to allow non-cubic world areas. For example the shape of T.
![image](https://user-images.githubusercontent.com/8858331/105573122-a49b9980-5d5b-11eb-9034-577d7f54eed7.png)

**Comment by nuriofernandez** [comment]
![image](https://user-images.githubusercontent.com/8858331/230752343-e0ed8fd4-fa4c-4adf-bf65-d310b7a81a43.png)

This is now possible:
```yml
name: "Redo"
uuid: "63b4809c-b73e-4a26-a106-4e722fe9c454"
areas:
  1:
    end:
      w: "world"
      x: -348
      y: 95
      z: 24
      yaw: 0
      pitch: 0
    start:
      w: "world"
      x: -346
      y: 110
      z: 22
      yaw: 0
      pitch: 0
  2:
    end:
      w: "world"
      x: -345
      y: 95
      z: 22
      yaw: 0
      pitch: 0
    start:
      w: "world"
      x: -340
      y: 110
      z: 20
      yaw: 0
      pitch: 0
  3:
    end:
      w: "world"
      x: -343
      y: 95
      z: 23
      yaw: 0
      pitch: 0
    start:
      w: "world"
      x: -345
      y: 110
      z: 26
      yaw: 0
      pitch: 0
```
